# Generated by Django 3.1.5 on 2021-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberPW',
            field=models.CharField(max_length=200),
        ),
    ]
