# Generated by Django 3.1.5 on 2021-02-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yyApp', '0002_remove_pet_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='postID',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='yyApp.board'),
        ),
    ]
