# Generated by Django 3.1.5 on 2021-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yyApp', '0003_pet_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
